// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBill = "bill"

// Bill mapped from table <bill>
type Bill struct {
	ID          int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	OperationID int64 `gorm:"column:operation_id;type:int;not null" json:"operation_id"`
	Balance     int64 `gorm:"column:balance;type:int;not null" json:"balance"`
	Deleted     int64 `gorm:"column:deleted;type:int;not null;default:100" json:"deleted"`
	Created     int64 `gorm:"column:created;type:int" json:"created"`
}

// TableName Bill's table name
func (*Bill) TableName() string {
	return TableNameBill
}
