// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFund = "funds"

// Fund mapped from table <funds>
type Fund struct {
	ID     int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID int64 `gorm:"column:user_id;type:int;not null" json:"user_id"`
	Money  int64 `gorm:"column:money;type:int;not null" json:"money"`
}

// TableName Fund's table name
func (*Fund) TableName() string {
	return TableNameFund
}
