// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLable = "lable"

// Lable mapped from table <lable>
type Lable struct {
	ID    int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title string `gorm:"column:title;type:varchar(10);not null" json:"title"`
}

// TableName Lable's table name
func (*Lable) TableName() string {
	return TableNameLable
}
