// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMyteacher = "myteacher"

// Myteacher mapped from table <myteacher>
type Myteacher struct {
	ID        int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64 `gorm:"column:user_id;type:int;not null" json:"user_id"`
	TeacherID int64 `gorm:"column:teacher_id;type:int;not null" json:"teacher_id"`
	Created   int64 `gorm:"column:created;type:int" json:"created"`
}

// TableName Myteacher's table name
func (*Myteacher) TableName() string {
	return TableNameMyteacher
}
