// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMyteacherLable = "myteacher_lable"

// MyteacherLable mapped from table <myteacher_lable>
type MyteacherLable struct {
	ID          int64 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	MyteacherID int64 `gorm:"column:myteacher_id;type:int;not null" json:"myteacher_id"`
	LabelID     int64 `gorm:"column:label_id;type:int;not null" json:"label_id"`
}

// TableName MyteacherLable's table name
func (*MyteacherLable) TableName() string {
	return TableNameMyteacherLable
}
