// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRecharge = "recharge"

// Recharge mapped from table <recharge>
type Recharge struct {
	ID      int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title   string `gorm:"column:title;type:varchar(255);not null" json:"title"`
	UserID  int64  `gorm:"column:user_id;type:int;not null" json:"user_id"`
	Sum     int64  `gorm:"column:sum;type:int;not null" json:"sum"` // 金额
	Created int64  `gorm:"column:created;type:int" json:"created"`
}

// TableName Recharge's table name
func (*Recharge) TableName() string {
	return TableNameRecharge
}
