// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID    int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title string `gorm:"column:title;type:varchar(10);not null" json:"title"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
