// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubject = "subject"

// Subject mapped from table <subject>
type Subject struct {
	ID        int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Title     string `gorm:"column:title;type:varchar(10);not null" json:"title"`
	Content   string `gorm:"column:content;type:varchar(255);not null" json:"content"`
	TeacherID int64  `gorm:"column:teacher_id;type:int;not null" json:"teacher_id"`
	UnitPrice int64  `gorm:"column:unit_price;type:int;not null" json:"unit_price"`
	Created   int64  `gorm:"column:created;type:int" json:"created"`
}

// TableName Subject's table name
func (*Subject) TableName() string {
	return TableNameSubject
}
