// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTeacher = "teacher"

// Teacher mapped from table <teacher>
type Teacher struct {
	ID      int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name    string `gorm:"column:name;type:varchar(10);not null" json:"name"`
	Source  string `gorm:"column:source;type:varchar(10)" json:"source"`
	City    string `gorm:"column:city;type:varchar(20)" json:"city"`
	Created int64  `gorm:"column:created;type:int" json:"created"`
}

// TableName Teacher's table name
func (*Teacher) TableName() string {
	return TableNameTeacher
}
