// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Username string `gorm:"column:username;type:varchar(20);not null" json:"username"`
	Password string `gorm:"column:password;type:varchar(255);not null" json:"password"`
	RoleID   int64  `gorm:"column:role_id;type:int;not null;default:1" json:"role_id"`
	Photo    string `gorm:"column:photo;type:varchar(255)" json:"photo"`
	Status   int64  `gorm:"column:status;type:int;default:1" json:"status"`
	Created  int64  `gorm:"column:created;type:int" json:"created"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
